### ISSUE TITLE
ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted.

### ISSUE THREAD

**Issue by srinivasanBG** [clockin/react-native-login-twitter#8]
Hi,

Am facing this issue when i upload to appStoreConnect.
Please help me to resolve this.

Thanks.

**Comment by srinivasanBG** [comment]
Please help me on this above issue.

**Comment by sordev** [comment]
Somehow the change in 
https://github.com/clockin/react-native-login-twitter/blob/master/react-native-login-twitter.podspec
#18 
is not getting reflected at npm repo so you have to manually change that into TwitterKit5
